module.exports =  {
    college: 
        [
            {
                "id": 1,
                "name": "College of Engineering Pune",
                "address": "Wellesley Road, Shivajinagar, Ludhiana, Punjab, India Pin: 411005",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 15th",
                "naac": "NAAC A+",
                "date_of_estb": "Date of establishment : 1854",
                "contact": "+91 20 25507000",
                "principal": "Dr. B.B. Ahuja",
                "email": "Email : principal@coep.ac.in",
                "website": "http://www.coep.org.in/"
            },
            {
                "id": 2,
                "name": "MIT World Peace University, Pune",
                "address": "Kothrud, Ambala, Haryana, India Pin: 411038",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 138th",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1983",
                "contact": "+91 20 30273600",
                "principal": "Dr. Mangesh Karad",
                "email": "Email : info@mitwpu.edu.in",
                "website": "http://www.mitwpu.edu.in/"
            },
            {
                "id": 3,
                "name": "Vishwakarma Institute of Technology",
                "address": "666, Upper Indiranagar, Jagadri, Haryana India Pin: 411037",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 101st",
                "naac": "NAAC B",
                "date_of_estb": "Date of establishment : 1983",
                "contact": "+91 20 24202250",
                "principal": "Dr. Rajesh Jalnekar",
                "email": "Email : principal@vit.edu",
                "website": "http://www.vit.edu/"
            },
            {
                "id": 4,
                "name": "Pune Institute of Computer Technology",
                "address": "Survey No. 27, Dhankawadi, Ludhiana, Punjab, India Pin: 411043",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 201-250",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1983",
                "contact": "+91 20 24372061",
                "principal": "Dr. Gajanan Kharate",
                "email": "Email : principal@pict.edu",
                "website": "http://www.pict.edu/"
            },
            {
                "id": 5,
                "name": "Bharati Vidyapeeth Deemed University College of Engineering",
                "address": "Pune-Satara Road, Dhankawadi, Pune, Maharashtra, India Pin: 411043",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 101-150",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1983",
                "contact": "+91 20 24107390",
                "principal": "Dr. Anand Bhalerao",
                "email": "Email : principal@bvcoe.bharatividyapeeth.edu",
                "website": "http://www.bvucoep.edu.in/"
            },
            {
                "id": 6,
                "name": "MIT College of Engineering",
                "address": "Paud Road, Kothrud, Mohali, Punjab, India Pin: 411038",
                "university": "University : Punjab University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC B",
                "date_of_estb": "Date of establishment : 2000",
                "contact": "+91 20 30273400",
                "principal": "Dr. S. S. Pande",
                "email": "Email : principal@mitcoe.edu.in",
                "website": "http://www.mitcoe.edu.in/"
            },
            {
                "id": 7,
                "name": "AISSMS College of Engineering",
                "address": "Kennedy Road, Near R.T.O, Ambala, Haryana, India Pin: 411001",
                "university": "University : Haryana University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC B++",
                "date_of_estb": "Date of establishment : 1992",
                "contact": "+91 20 26058342",
                "principal": "Dr. P.B. Mane",
                "email": "Email : principal@aissmscoe.com",
                "website": "http://www.aissmscoe.com/"
            },
            {
                "id": 8,
                "name": "Sinhgad College of Engineering",
                "address": "S. No. 44/1, Vadgaon(Bk.), Off Sinhgad Road, Patna, Bihar, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC B+",
                "date_of_estb": "Date of establishment : 1996",
                "contact": "+91 20 24354705",
                "principal": "Dr. M. N. Navale",
                "email": "Email : principal.scoe@sinhgad.edu",
                "website": "http://www.sinhgad.edu/"
            },
            {
                "id": 9,
                "name": "Pimpri Chinchwad College of Engineering",
                "address": "Sector 26, Pradhikaran, Nigdi, Pune, Maharashtra, India Pin: 411044",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 27653168",
                "principal": "Dr. A. M. Fulambarkar",
                "email": "Email : principal@pccoepune.org",
                "website": "http://www.pccoepune.org/"
            },
            {
                "id": 10,
                "name": "Army Institute of Technology",
                "address": "Dighi Hills, Alandi Road, Pune, Maharashtra, India Pin: 411015",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 101-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1994",
                "contact": "+91 20 27157612",
                "principal": "Brigadier A. S. Sahrawat",
                "email": "Email : ait@aitpune.edu.in",
                "website": "http://www.aitpune.com/"
            },
            {
                "id": 11,
                "name": "Dr. D.Y. Patil Institute of Technology",
                "address": "Sant Tukaram Nagar, Pimpri, Pune, Maharashtra, India Pin: 411018",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1998",
                "contact": "+91 20 27421095",
                "principal": "Dr. P. D. Patil",
                "email": "Email : principal@dypcoeakurdi.ac.in",
                "website": "http://www.dypcoeakurdi.ac.in/"
            },
            {
                "id": 12,
                "name": "Vishwakarma Institute of Information Technology",
                "address": "Survey No. 2, 3, 4, Kondhwa Budruk, Pune, Maharashtra, India Pin: 411048",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 101-150",
                "naac": "NAAC C",
                "date_of_estb": "Date of establishment : 2002",
                "contact": "+91 20 26950355",
                "principal": "Dr. Leena Ramachandran",
                "email": "Email : principal@viit.ac.in",
                "website": "http://www.viit.ac.in/"
            },
            {
                "id": 13,
                "name": "Cummins College of Engineering for Women",
                "address": "Karvenagar, Pune, Maharashtra, India Pin: 411052",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC C",
                "date_of_estb": "Date of establishment : 1991",
                "contact": "+91 20 25311000",
                "principal": "Dr. A.B. Kharat",
                "email": "Email : principal@cumminscollege.edu.in",
                "website": "http://www.cumminscollege.edu.in/"
            },
            {
                "id": 14,
                "name": "MIT Academy of Engineering",
                "address": "Alandi, Pune, Maharashtra, India Pin: 412105",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC C",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 30273600",
                "principal": "Dr. Y.J. Bhalerao",
                "email": "Email : principal@mitaoe.ac.in",
                "website": "http://www.mitaoe.ac.in/"
            },
            {
                "id": 15,
                "name": "DY Patil College of Engineering",
                "address": "Akurdi, Pune, Maharashtra, India Pin: 411044",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100",
                "naac": "NAAC B",
                "date_of_estb": "Date of establishment : 1984",
                "contact": "+91 20 27654512",
                "principal": "Dr. N.J. Pawar",
                "email": "Email : principal@dypcoeakurdi.ac.in",
                "website": "http://www.dypcoeakurdi.ac.in/"
            },
            {
                "id": 16,
                "name": "Trinity College of Engineering and Research",
                "address": "Kondhwa Annex, Pune, Maharashtra, India Pin: 411048",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 101",
                "naac": "NAAC B++",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 26950867",
                "principal": "Dr. V.G. Gaikar",
                "email": "Email : principal@tcet.edu.in",
                "website": "http://www.tcet.edu.in/"
            },
            {
                "id": 17,
                "name": "Marathwada Mitra Mandal’s College of Engineering",
                "address": "Karvenagar, Pune, Maharashtra, India Pin: 411052",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2006",
                "contact": "+91 20 25473159",
                "principal": "Dr. V. M. Deshpande",
                "email": "Email : principal@mmcoe.edu.in",
                "website": "http://www.mmcoe.edu.in/"
            },
            {
                "id": 18,
                "name": "Indira College of Engineering and Management",
                "address": "Parandwadi, Pune, Maharashtra, India Pin: 410506",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC D",
                "date_of_estb": "Date of establishment : 2007",
                "contact": "+91 20 66759595",
                "principal": "Dr. G.R. Khadse",
                "email": "Email : principal@indiraicem.ac.in",
                "website": "http://www.indiraicem.ac.in/"
            },
            {
                "id": 19,
                "name": "Sinhgad Institute of Technology and Science",
                "address": "Narhe, Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 24100205",
                "principal": "Dr. S. R. Kale",
                "email": "Email : principal@sinhgad.edu",
                "website": "http://www.sinhgad.edu/"
            },
            {
                "id": 20,
                "name": "MIT School of Engineering",
                "address": "Rajbaug, Loni Kalbhor, Pune, Maharashtra, India Pin: 412201",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC D",
                "date_of_estb": "Date of establishment : 2017",
                "contact": "+91 20 39210000",
                "principal": "Dr. D. G. Kumbhar",
                "email": "Email : principal@mitsoe.edu.in",
                "website": "http://www.mitsoe.edu.in/"
            },
            {
                "id": 21,
                "name": "Pune Vidyarthi Griha's College of Engineering and Technology",
                "address": "44, Vidya Nagari, Shiv Darshan, Parvati, Pune, Maharashtra, India Pin: 411009",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1985",
                "contact": "+91 20 24228258",
                "principal": "Dr. N. J. Pawar",
                "email": "Email : principal@pvgcoet.ac.in",
                "website": "http://www.pvgcoet.ac.in/"
            },
            {
                "id": 22,
                "name": "Rajiv Gandhi Institute of Technology",
                "address": "Andheri, Patna, Bihar, India Pin: 411053",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1991",
                "contact": "+91 20 27654687",
                "principal": "Dr. K. P. Adhi",
                "email": "Email : principal@rgit.edu",
                "website": "http://www.rgit.edu/"
            },
            {
                "id": 23,
                "name": "Nutan Maharashtra Institute of Engineering and Technology",
                "address": "Vishnupuri, Talegaon Dabhade, Varanasi, Uttar Pradesh, India Pin: 410507",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 27651234",
                "principal": "Dr. N. S. Desai",
                "email": "Email : principal@nmitpune.edu.in",
                "website": "http://www.nmitpune.edu.in/"
            },
            {
                "id": 24,
                "name": "All India Shri Shivaji Memorial Society's College of Engineering",
                "address": "Kennedy Road, Kanpur, Uttar Pradesh, India Pin: 411001",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1992",
                "contact": "+91 20 26057792",
                "principal": "Dr. D. N. Patil",
                "email": "Email : principal@aissmscoe.com",
                "website": "http://www.aissmscoe.com/"
            },
            {
                "id": 25,
                "name": "Jayawantrao Sawant College of Engineering",
                "address": "S. No. 58, Handewadi Road, Hadapsar, Pune, Maharashtra, India Pin: 411028",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2004",
                "contact": "+91 20 26970229",
                "principal": "Dr. A. G. Patil",
                "email": "Email : principal@jspm.edu.in",
                "website": "http://www.jspm.edu.in/"
            },
            {
                "id": 26,
                "name": "Zeal College of Engineering and Research",
                "address": "Narhe, Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2007",
                "contact": "+91 20 24109100",
                "principal": "Dr. V. R. Patil",
                "email": "Email : principal@zcoer.in",
                "website": "http://www.zcoer.in/"
            },
            {
                "id": 27,
                "name": "G H Raisoni College of Engineering and Management",
                "address": "Pune-Ahmednagar Highway, Wagholi, Pune, Maharashtra, India Pin: 412207",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2007",
                "contact": "+91 20 27070000",
                "principal": "Dr. P. G. Mehta",
                "email": "Email : principal@ghrce.edu.in",
                "website": "http://www.ghrce.edu.in/"
            },
            {
                "id": 28,
                "name": "KJ College of Engineering and Management Research",
                "address": "Pisoli, Pune, Maharashtra, India Pin: 411048",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2009",
                "contact": "+91 20 26970230",
                "principal": "Dr. R. J. Patil",
                "email": "Email : principal@kjcoe.edu.in",
                "website": "http://www.kjcoe.edu.in/"
            },
            {
                "id": 29,
                "name": "Dr. D.Y. Patil School of Engineering and Technology",
                "address": "Lohegaon, Mumbai, Maharashtra, India Pin: 411047",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2010",
                "contact": "+91 20 27650346",
                "principal": "Dr. D. M. Kulkarni",
                "email": "Email : principal@dypsoet.ac.in",
                "website": "http://www.dypsoet.ac.in/"
            },
            {
                "id": 30,
                "name": "Dhole Patil College of Engineering",
                "address": "Wagholi, Mumbai, Maharashtra, India Pin: 412207",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 27052794",
                "principal": "Dr. A. A. Kulkarni",
                "email": "Email : principal@dpcoe.edu.in",
                "website": "http://www.dpcoe.edu.in/"
            },
            {
                "id": 31,
                "name": "Smt. Kashibai Navale College of Engineering",
                "address": "Vadgaon(Bk.), Off Sinhgad Road, Mumbai, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2001",
                "contact": "+91 20 24100000",
                "principal": "Dr. S. B. Chitalkar",
                "email": "Email : principal@skncoe.edu.in",
                "website": "http://www.skncoe.edu.in/"
            },
            {
                "id": 32,
                "name": "Genba Sopanrao Moze College of Engineering",
                "address": "Balewadi, Lucknow, Uttar Pradesh, India Pin: 411045",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 27805364",
                "principal": "Dr. S. M. Kulkarni",
                "email": "Email : principal@gsmoze.edu.in",
                "website": "http://www.gsmoze.edu.in/"
            },
            {
                "id": 33,
                "name": "Maharashtra Academy of Engineering",
                "address": "Alandi, Mumbai, Maharashtra, India Pin: 412105",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 144",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 30273600",
                "principal": "Dr. N. S. Desai",
                "email": "Email : principal@mae.edu.in",
                "website": "http://www.mae.edu.in/"
            },
            {
                "id": 34,
                "name": "Pimpri Chinchwad College of Engineering and Research",
                "address": "Ravet, Pune, Maharashtra, India Pin: 412101",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2014",
                "contact": "+91 20 27653400",
                "principal": "Dr. S. V. Aher",
                "email": "Email : principal@pccoe.org",
                "website": "http://www.pccoe.org/"
            },
            {
                "id": 35,
                "name": "DY Patil Institute of Technology and Engineering",
                "address": "Ambi, Pune, Maharashtra, India Pin: 410507",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2012",
                "contact": "+91 20 27650345",
                "principal": "Dr. P. R. Patil",
                "email": "Email : principal@dypcoeambi.edu.in",
                "website": "http://www.dypcoeambi.edu.in/"
            },
            {
                "id": 36,
                "name": "Sandip Institute of Technology and Research Center",
                "address": "Nashik, Pune, Maharashtra, India Pin: 422213",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 25860000",
                "principal": "Dr. R. K. Sharma",
                "email": "Email : principal@sitrc.edu.in",
                "website": "http://www.sitrc.edu.in/"
            },
            {
                "id": 37,
                "name": "Rajarshi Shahu College of Engineering",
                "address": "Tathawade, Pune, Maharashtra, India Pin: 411033",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 100-150",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2001",
                "contact": "+91 20 27400000",
                "principal": "Dr. R. S. Yadav",
                "email": "Email : principal@rscoe.edu.in",
                "website": "http://www.rscoe.edu.in/"
            },
            {
                "id": 38,
                "name": "NBN Sinhgad School of Engineering",
                "address": "Ambegaon (Bk.), Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 156",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2010",
                "contact": "+91 20 24351439",
                "principal": "Dr. S. V. Kulkarni",
                "email": "Email : principal@nbnsinhgad.edu.in",
                "website": "http://www.nbnsinhgad.edu.in/"
            },
            {
                "id": 39,
                "name": "PES Modern College of Engineering",
                "address": "Off. Pashan Road, Pune, Maharashtra, India Pin: 411052",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 152",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 25632406",
                "principal": "Dr. S. P. Sonavane",
                "email": "Email : principal@pesmcoepune.org",
                "website": "http://www.pesmcoepune.org/"
            },
            {
                "id": 40,
                "name": "Sinhgad Academy of Engineering",
                "address": "Kondhwa-Saswad Road, Kondhwa (Bk.), Pune, Maharashtra, India Pin: 411048",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2010",
                "contact": "+91 20 26934401",
                "principal": "Dr. A. S. Deshpande",
                "email": "Email : principal@sinhgad.edu",
                "website": "http://www.sinhgad.edu/"
            },
            {
                "id": 41,
                "name": "Genba Sopanrao Moze College of Engineering, Baner",
                "address": "Baner-Balewadi Road, Pune, Maharashtra, India Pin: 411045",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2011",
                "contact": "+91 20 27292181",
                "principal": "Dr. R. S. Shelar",
                "email": "Email : principal@gsmcoe.ac.in",
                "website": "http://www.gsmcoe.ac.in/"
            },
            {
                "id": 42,
                "name": "Dr. D.Y. Patil School of Engineering & Technology, Lohegaon",
                "address": "Charoli Bk. Via Lohegaon, Pune, Maharashtra, India Pin: 412105",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 2011",
                "contact": "+91 20 27051000",
                "principal": "Dr. S. S. Lokhande",
                "email": "Email : principal@dypsoetl.edu.in",
                "website": "http://www.dypsoetl.edu.in/"
            },
            {
                "id": 43,
                "name": "Dr. D.Y. Patil Institute of Engineering & Technology, Pimpri",
                "address": "Pimpri, Pune, Maharashtra, India Pin: 411018",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1998",
                "contact": "+91 20 27422159",
                "principal": "Dr. S. S. Sambare",
                "email": "Email : principal@engg.dypvp.edu.in",
                "website": "http://engg.dypvp.edu.in/"
            },
            {
                "id": 44,
                "name": "Pimpri Chinchwad College of Engineering & Research, Ravet",
                "address": "Sector 26, Pradhikaran, Nigdi, Ravet, Pune, Maharashtra, India Pin: 412101",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A++",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 27653168",
                "principal": "Dr. A. M. Fulambarkar",
                "email": "Email : principal@pccoer.in",
                "website": "http://www.pccoer.com/"
            },
            {
                "id": 45,
                "name": "Bharati Vidyapeeth College of Engineering, Lavale",
                "address": "Survey No. 63, Near Katraj Dairy, Dhankawadi, Mumbai, Maharashtra, India Pin: 411041",
                "university": "University : Bharati Vidyapeeth (Deemed University)",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2012",
                "contact": "+91 20 24372867",
                "principal": "Dr. S. B. Somani",
                "email": "Email : principal@bvpcoelavale.edu.in",
                "website": "http://www.bvpcoelavale.edu.in/"
            },
            {
                "id": 46,
                "name": "Jayawantrao Sawant College of Engineering, Hadapsar",
                "address": "S. No. 58, Indrayani Nagar, Handewadi Road, Hadapsar, Mumbai, Maharashtra, India Pin: 411028",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2007",
                "contact": "+91 20 26970882",
                "principal": "Dr. V. R. Desai",
                "email": "Email : principal@jspm.edu.in",
                "website": "http://www.jspm.edu.in/"
            },
            {
                "id": 47,
                "name": "Alard College of Engineering & Management, Hinjewadi",
                "address": "Marunje, Hinjawadi, Pune, Maharashtra, India Pin: 411057",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2009",
                "contact": "+91 20 66523711",
                "principal": "Dr. R. M. Chavan",
                "email": "Email : principal@alardinstitutes.com",
                "website": "http://www.alardinstitutes.com/"
            },
            {
                "id": 48,
                "name": "MKSSS's Cummins College of Engineering for Women, Karvenagar",
                "address": "Karve Nagar, Mumbai, Maharashtra, India Pin: 411052",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1991",
                "contact": "+91 20 25311000",
                "principal": "Dr. S. R. Punde",
                "email": "Email : principal@cumminscollege.org",
                "website": "http://www.cumminscollege.org/"
            },
            {
                "id": 49,
                "name": "Sinhgad College of Engineering, Vadgaon",
                "address": "Vadgaon (BK), Off Sinhgad Road, Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1996",
                "contact": "+91 20 24354705",
                "principal": "Dr. S. V. Bonde",
                "email": "Email : principal@sinhgad.edu",
                "website": "http://www.sinhgad.edu/"
            },
            {
                "id": 50,
                "name": "Dr. D. Y. Patil Institute of Technology, Ambi",
                "address": "S. No. 124 & 126, A/p Ambi, M.I.D.C. Road, Taluka - Maval, Mumbai, Maharashtra, India Pin: 410506",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2014",
                "contact": "+91 20 25671703",
                "principal": "Dr. A. S. Kadam",
                "email": "Email : principal.engg@dyptcet.ac.in",
                "website": "http://engg.dypvp.edu.in/"
            },
            {
                "id": 51,
                "name": "Vishwakarma Institute of Information Technology, Kondhwa",
                "address": "Survey No. 3/4, Latur Road, Kondhwa Budruk, Pune, Maharashtra, India Pin: 411048",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2002",
                "contact": "+91 20 26932800",
                "principal": "Dr. S. R. Sathe",
                "email": "Email : principal@viit.ac.in",
                "website": "http://www.viit.ac.in/"
            },
            {
                "id": 52,
                "name": "Sinhgad Institute of Technology, Lonavala",
                "address": "S. No. 44/1, 44/1, Vadgaon (BK), Off Sinhgad Road, Pune, Maharashtra, India Pin: 410401",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2004",
                "contact": "+91 20 24354700",
                "principal": "Dr. P. K. Kulkarni",
                "email": "Email : principal@sit.lonavala.in",
                "website": "http://www.sit.lonavala.in/"
            },
            {
                "id": 53,
                "name": "Rajarshi Shahu College of Engineering, Tathawade",
                "address": "Survey No. 80, Pune-Mumbai Bypass Highway, Tathawade, Delhi, Maharashtra, India Pin: 411033",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2001",
                "contact": "+91 20 22933423",
                "principal": "Dr. K. P. Patil",
                "email": "Email : principal@rscoe.org",
                "website": "http://www.rscoe.org/"
            },
            {
                "id": 54,
                "name": "Smt. Kashibai Navale College of Engineering, Vadgaon (Bk.)",
                "address": "S. No. 44/1, 44/1, Vadgaon (BK), Off Sinhgad Road, Delhi, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2001",
                "contact": "+91 20 24354750",
                "principal": "Dr. S. R. Pande",
                "email": "Email : principal@skncoe.ac.in",
                "website": "http://www.skncoe.ac.in/"
            },
            {
                "id": 55,
                "name": "Sinhgad Institute of Technology & Science, Narhe",
                "address": "S. No. 40/4A+4B/1, 4B/2A, Narhe, Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 24699974",
                "principal": "Dr. U. P. Waghe",
                "email": "Email : principal@sitspune.edu.in",
                "website": "http://www.sitspune.edu.in/"
            },
            {
                "id": 56,
                "name": "Dr. D. Y. Patil School of Engineering, Lohegaon",
                "address": "S. No. 124 & 126, A/p Ambi, M.I.D.C. Road, Taluka - Maval, Pune, Maharashtra, India Pin: 410506",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2011",
                "contact": "+91 20 27653054",
                "principal": "Dr. N. J. Vyavahare",
                "email": "Email : principal.engg@dyptcet.ac.in",
                "website": "http://engg.dypvp.edu.in/"
            },
            {
                "id": 57,
                "name": "Pimpri Chinchwad College of Engineering, Pune",
                "address": "Sector -26, Pradhikaran, Nigdi, Near Akurdi Railway Station, Delhi, Maharashtra, India Pin: 411044",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 27653168",
                "principal": "Dr. R. B. Shelke",
                "email": "Email : principal@pccoepune.org",
                "website": "http://www.pccoepune.org/"
            },
            {
                "id": 58,
                "name": "Pune Institute of Computer Technology, Dhankawadi",
                "address": "S.No.27, Pune-Satara Road, Dhankawadi, Pune, Maharashtra, India Pin: 411043",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1983",
                "contact": "+91 20 24371101",
                "principal": "Dr. B. B. Ahuja",
                "email": "Email : principal@pict.edu",
                "website": "http://www.pict.edu/"
            },
            {
                "id": 59,
                "name": "Dhole Patil College of Engineering, Wagholi",
                "address": "S.No.27, Pune-Satara Road, Dhankawadi, Delhi, Maharashtra, India Pin: 411043",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 67077700",
                "principal": "Dr. N. P. Tandale",
                "email": "Email : principal@dypcoeakurdi.ac.in",
                "website": "http://www.dypcoeakurdi.ac.in/"
            },
            {
                "id": 60,
                "name": "Sinhgad Academy of Engineering, Kondhwa",
                "address": "Kondhwa-Saswad Road, Kondhwa (BK), Pune, Maharashtra, India Pin: 411048",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2007",
                "contact": "+91 20 26934060",
                "principal": "Dr. K. M. Raut",
                "email": "Email : principal@sinhgad.edu",
                "website": "http://www.sinhgad.edu/"
            },
            {
                "id": 61,
                "name": "All India Shri Shivaji Memorial Society's College of Engineering, Pune",
                "address": "Kennedy Road, Near R.T.O., Pune, Maharashtra, India Pin: 411001",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1992",
                "contact": "+91 20 26058587",
                "principal": "Dr. M. D. Kokate",
                "email": "Email : principal@aissmscoe.com",
                "website": "http://www.aissmscoe.com/"
            },
            {
                "id": 62,
                "name": "Marathwada Mitra Mandal's College of Engineering, Karvenagar",
                "address": "Sr. No. 35, Plot No. 5/6, Karve Road, Karvenagar, Delhi, Maharashtra, India Pin: 411052",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2006",
                "contact": "+91 20 25454582",
                "principal": "Dr. R. P. Labade",
                "email": "Email : principal@mmcoe.edu.in",
                "website": "http://www.mmcoe.edu.in/"
            },
            {
                "id": 63,
                "name": "Sinhgad Institute of Technology, Lonavala",
                "address": "S. No. 44/1, 44/1, Vadgaon (BK), Off Sinhgad Road, Pune, Maharashtra, India Pin: 410401",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2004",
                "contact": "+91 20 24354700",
                "principal": "Dr. P. K. Kulkarni",
                "email": "Email : principal@sit.lonavala.in",
                "website": "http://www.sit.lonavala.in/"
            },
            {
                "id": 64,
                "name": "Pimpri Chinchwad College of Engineering & Research, Ravet",
                "address": "Sector -26, Pradhikaran, Nigdi, Near Akurdi Railway Station, Pune, Maharashtra, India Pin: 411044",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2012",
                "contact": "+91 20 27653168",
                "principal": "Dr. S. M. Deshmukh",
                "email": "Email : principal@pccoerpune.org",
                "website": "http://www.pccoerpune.org/"
            },
            {
                "id": 65,
                "name": "Sinhgad Institute of Technology, Lonavala",
                "address": "S. No. 44/1, 44/1, Vadgaon (BK), Off Sinhgad Road, Pune, Maharashtra, India Pin: 410401",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2004",
                "contact": "+91 20 24354700",
                "principal": "Dr. P. K. Kulkarni",
                "email": "Email : principal@sit.lonavala.in",
                "website": "http://www.sit.lonavala.in/"
            },
            {
                "id": 66,
                "name": "Sinhgad College of Engineering, Kondhwa",
                "address": "S. No. 44/1, 44/1, Vadgaon (BK), Off Sinhgad Road, Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1996",
                "contact": "+91 20 24354705",
                "principal": "Dr. S. V. Bonde",
                "email": "Email : principal@sinhgad.edu",
                "website": "http://www.sinhgad.edu/"
            },
            {
                "id": 67,
                "name": "Sinhgad Institute of Technology & Science, Narhe",
                "address": "S. No. 40/4A+4B/1, 4B/2A, Narhe, Pune, Maharashtra, India Pin: 411041",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2008",
                "contact": "+91 20 24699974",
                "principal": "Dr. U. P. Waghe",
                "email": "Email : principal@sitspune.edu.in",
                "website": "http://www.sitspune.edu.in/"
            },
            {
                "id": 68,
                "name": "Pune Vidyarthi Griha's College of Engineering & Technology, Pune",
                "address": "44, Vidyanagari, Parvati, Pune, Maharashtra, India Pin: 411009",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1985",
                "contact": "+91 20 24228258",
                "principal": "Dr. R. G. Kulkarni",
                "email": "Email : principal@pvgcoet.ac.in",
                "website": "http://www.pvgcoet.ac.in/"
            },
            {
                "id": 69,
                "name": "Maharashtra Academy of Engineering, Alandi",
                "address": "Sr. No. 124, MIT College Campus, Paud Road, Kothrud, Pune, Maharashtra, India Pin: 411038",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1999",
                "contact": "+91 20 30273506",
                "principal": "Dr. P. M. Padole",
                "email": "Email : principal@mitaoe.ac.in",
                "website": "http://www.mitaoe.ac.in/"
            },
            {
                "id": 70,
                "name": "Jayawant Shikshan Prasarak Mandal's Rajarshi Shahu College of Engineering, Tathawade",
                "address": "Sr. No. 35, Plot No. 5/6, Karve Road, Karvenagar, Pune, Maharashtra, India Pin: 411052",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2007",
                "contact": "+91 20 22933423",
                "principal": "Dr. K. P. Patil",
                "email": "Email : principal@rscoe.org",
                "website": "http://www.rscoe.org/"
            },
            {
                "id": 71,
                "name": "Pune Institute of Computer Technology, Dhankawadi",
                "address": "S.No.27, Pune-Satara Road, Dhankawadi, Pune, Maharashtra, India Pin: 411043",
                "university": "University : Savitribai Phule Pune University",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 1983",
                "contact": "+91 20 24371101",
                "principal": "Dr. B. B. Ahuja",
                "email": "Email : principal@pict.edu",
                "website": "http://www.pict.edu/"
            },
            {
                "id": 72,
                "name": "International Institute of Information Technology",
                "address": "Rajiv Gandhi Infotech Park, Hinjawadi, Delhi, Maharashtra, India Pin: 411057",
                "university": "University : Autonomous",
                "nirf": "NIRF 151-200",
                "naac": "NAAC A",
                "date_of_estb": "Date of establishment : 2003",
                "contact": "+91 20 22933423",
                "principal": "Dr. P. K. Singh",
                "email": "Email : principal@iiitp.ac.in",
                "website": "http://www.iiitp.ac.in/"
            },
                
        ]
};